# Generated by Django 3.2.4 on 2021-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="id",),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
